services:
  marzban:
    image: gozargah/marzban:latest
    container_name: free_vpn_bot_marzban
    restart: always
    env_file: .env.marzban
    environment:
      UVICORN_HOST: "marzban"
      UVICORN_PORT: "8001"
      YOUR_DOMAIN: ${DOMAIN}
    ports:
      - "8001:8001"
    networks:
      - free_vpn_bot
    volumes:
      - marz-storage:/code
      - ./volumes/marzban:/var/lib/marzban
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "900k"
        max-file: "10"
  vpn_bot:
    image: free_vpn_bot
    container_name: "vpn_bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - free_vpn_bot
    depends_on:
      - marzban
networks:
  free_vpn_bot:
    driver: bridge

volumes:
  marz-storage:
    driver: local